---
- name: ISE - SWITCH CONFIGURATION
  hosts: switches
  gather_facts: false
  
  tasks:
    - name: Enable AAA
      ios_config:
        lines:
          - aaa new-model

    - name: Configure RADIUS servers
      ios_config:
        parents: "radius server {{ item.name }}"
        lines:
          - address ipv4 {{ item.Ip }} auth-port 1812 acct-port 1813
          - key {{ item.key }}
      loop: "{{ ise_servers }}"
      no_log: true

    - name: Configure RADIUS server group
      ios_config:
        parents: "aaa group server radius {{ aaa_group }}"
        lines:
          - "server name {{ item.name }}"
      loop: "{{ ise_servers }}"
      no_log: true

    - name: Configure AAA authentication, authorization and accounting
      ios_config:
        lines:
          - aaa authentication dot1x default group {{ aaa_group }}
          - aaa authorization network default group {{ aaa_group }}
          - aaa authorization auth-proxy default group {{ aaa_group }}
          - aaa accounting dot1x default start-stop group {{ aaa_group }}
          - aaa session-id common
          - aaa accounting update periodic 5
          - aaa accounting system default start-stop group {{ aaa_group }}

    - name: Configure local user for testing
      ios_config:
        lines:
          - "username {{ radius_user }} password 0 {{ radius_password }}"

    - name: Enable HTTP and HTTPS servers
      ios_config:
        lines:
          - ip http server
          - ip http secure-server

    - name: Enable radius attributes for ISE
      ios_config:
        lines:
          - radius-server vsa send accounting
          - radius-server vsa send authentication
          - radius-server attribute 6 on-for-login-auth
          - radius-server attribute 6 support-multiple
          - radius-server attribute 8 include-in-access-req
          - radius-server attribute 25 access-request include
          - radius-server dead-criteria time 10 tries 3
          - radius-server deadtime 30
          - radius-server attribute 31 mac format ietf upper-case
          - radius-server attribute 31 send nas-port-detail

    - name: Configure source interface for RADIUS and SNMP
      ios_config:
        lines:
          - ip radius source-interface {{ source_interface }}
          - snmp-server trap-source {{ source_interface }}
          - snmp-server source-interface inform {{ source_interface }}

    - name: Enable 802.1X and device tracking
      ios_config:
        lines:
          - dot1x system-auth-control
          - ip device tracking
          - ip device tracking probe auto-source
          - device-sensor accounting
          - device-sensor notify all-changes
          - dot1x critical eapol
          - authentication critical recovery delay 1000

    - name: Enable EPM logging
      ios_config:
        lines:
          - epm logging

    - name: Configure ACL-DEFAULT
      ios_config:
        lines:
          - ip access-list extended ACL-DEFAULT
          - remark Autoriser DHCP
          - permit udp any eq bootpc any eq bootps
          - remark Autoriser DNS
          - permit udp any any eq domain
          - permit tcp any any eq domain
          - remark Bloquer le reste
          - deny ip any any

    - name: Configure access interfaces
      ios_config:
        parents: "interface {{ item }}"
        lines:
          - switchport mode access
          - spanning-tree portfast
          - spanning-tree bpduguard enable
          - authentication event fail action next-method
          - authentication event server dead action authorize voice
          - authentication event server dead action reinitialize vlan {{ vlan_dead }}
          - authentication timer reauthenticate server
          - authentication timer inactivity server
          - authentication host-mode multi-auth
          - authentication open
          - authentication order dot1x mab
          - authentication priority dot1x mab
          - authentication port-control auto
          - authentication violation restrict
          - authentication periodic
          - mab
          - dot1x pae authenticator
          - dot1x timeout tx-period 10
          - dot1x max-reauth-req 3
          - ip access-group ACL-DEFAULT in
      loop: "{{ access_interfaces }}"

    - name: Save running config
      ios_config:
        save_when: changed

