---
- name: ISE - SWITCH CONFIGURATION
  hosts: switches
  gather_facts: false
  
  tasks:
    - name: Enable AAA
      ios_config:
        lines:
          - aaa new-model

    - name: Configure RADIUS servers
      ios_config:
        parents: "radius server {{ item.name }}"
        lines:
          - address ipv4 {{ item.Ip }} auth-port 1812 acct-port 1813
          - key {{ item.key }}
      loop: "{{ ise_servers }}"
      no_log: true

    - name: Configure RADIUS server group
      ios_config:
        parents: "aaa group server radius {{ aaa_group }}"
        lines:
          - "server name {{ item.name }}"
      loop: "{{ ise_servers }}"
      no_log: true

    - name: Configure AAA authentication, authorization and accounting
      ios_config:
        lines:
          - aaa authentication dot1x default group {{ aaa_group }}
          - aaa authorization network default group {{ aaa_group }}
          - aaa authorization auth-proxy default group {{ aaa_group }}
          - aaa accounting dot1x default start-stop group {{ aaa_group }}
          - aaa session-id common
          - aaa accounting update periodic {{ update_period }}
          - aaa accounting system default start-stop group {{ aaa_group }}

    - name: Configure a local user for testing
      ansible.netcommon.cli_config:
        config: |
          username {{ radius_user }} password 0 {{ radius_password }}

    - name: Enable HTTP and HTTPS servers
      ios_config:
        lines:
          - ip http server
          - ip http secure-server

    - name: Enable radius attributes for ISE
      ios_config:
        lines:
          - radius-server vsa send accounting
          - radius-server vsa send authentication
          - radius-server attribute 6 on-for-login-auth
          - radius-server attribute 8 include-in-access-req
          - radius-server attribute 25 access-request include
          - radius-server attribute 31 mac format ietf upper-case

    - name: Configure source interface for RADIUS and SNMP
      ios_config:
        lines:
          - ip radius source-interface {{ source_interface }}
          - snmp-server trap-source {{ source_interface }}
          - snmp-server source-interface informs {{ source_interface }}

    - name: Enable 802.1X and device tracking
      ios_config:
        lines:
          - dot1x system-auth-control
          - ip device tracking
          - ip device tracking probe auto-source
          - ip device tracking probe delay 10
          - device-sensor accounting
          - device-sensor notify all-changes
          - dot1x critical eapol

    - name: Configure ACL-DEFAULT
      ios_config:
        parents: ip access-list extended ACL-ALLOW
        lines:
          - permit ip any any
          - ip access-list extended ACL-DEFAULT
          - remark DHCP
          - permit udp any eq bootpc any eq bootps
          - remark DNS
          - permit udp any any eq domain
          - remark Ping
          - permit icmp any any
          - remark PXE / TFTP
          - permit udp any any eq tftp
          - remark Drop all the rest
          - deny ip any any log

    - name: Configure ACL-WEBAUTH-REDIRECT
      ios_config:
        parents: ip access-list extended ACL-WEBAUT-REDIRECT
        lines:
          - remark explicitly deny DNS from being redirected
          - deny udp any any eq 53
          - remark redirect all applicable traffic to the ISE Server
          - permit tcp any any eq 80
          - permit tcp any any eq 443

    - name: Configure access interfaces
      ios_config:
        match: line
        parents: "interface {{ item }}"
        lines:
          - switchport mode access
          - spanning-tree portfast
          - spanning-tree bpduguard enable
          - authentication event fail action next-method
          - authentication event server dead action authorize vlan {{ vlan_dead }}
          - authentication event server dead action authorize voice
          - authentication event server alive action reinitialize
          - authentication timer reauthenticate server
          - authentication timer inactivity server
          - authentication open
          - authentication host-mode multi-auth
          - authentication priority dot1x mab
          - authentication order dot1x mab
          - authentication violation restrict
          - authentication periodic
          - mab
          - dot1x pae authenticator
          - dot1x timeout tx-period 10
          - ip access-group ACL-ALLOW in
          - authentication port-control auto
      loop: "{{ access_interfaces }}"
