---
- name: ADD END DEVICE CONNECTED INTERFACES
  hosts: switches
  gather_facts: false

  vars:
    output_file: "ansible_files/host_vars/{{ inventory_hostname }}.yml"  # Path to the existing YAML file

  tasks:
    - name: Retrieve all interfaces from each switch 
      ios_command:
        commands:
          - "show interfaces status"
      register: interface_status

    - name: Filter interfaces
      set_fact:
        access_interfaces: "{{ access_interfaces | default([]) + [item.split()[0]] }}"
      with_items: "{{ interface_status.stdout[0].splitlines() }}"
      when: "'trunk' not in item and item.split()[2] | string"
      no_log: true

    - name: Add specific interfaces to each switch's variable file 
      lineinfile:      
        path: "{{ output_file }}"
        line: "access_interfaces: {{ access_interfaces | reject('equalto', 'Port')|list }}"
        create: yes
        insertafter: EOF
